### ISSUE TITLE
AttributeError: module 'django.db.models' has no attribute 'ForiegnKey'

### ISSUE THREAD

**Issue by Aju100** [iw-academy-project/iw-acad-hamro-note-be#9]
I have implemented the Django blog model and I got the problems when I want to import registered users.

**Steps to Produce bug**
- First of all clone the project and unregister the blog app
- migrate app with built-in models
- register blog app and uncomment below code
`    #user = models.ForiegnKey(User,on_delete = models.CASCADE)
`

**Output:**
In the console, you can see this error AttributeError: module 'django.db.models' has no attribute 'ForiegnKey'

**Comment by AnjalBam** [comment]
This is a typo... ForeignKey
